### PR TITLE
AGPushAnalytics

### PR DESCRIPTION
**Pull request by corinnekrych**
Send Metrics in ObjC

this Pr is to merge in 1.x_dev branch

### CODE REVIEW

**Comment by corinnekrych** [comment]
@matzew could you review it pls? Demos apps are availabale: https://github.com/jboss-mobile/unified-push-helloworld/pull/7

**Comment by cvasilak** [comment]
:eyes: on it

**Comment by cvasilak** [comment]
for consistency with the swift port, mind to also port the [AGPushAnalyticsTests](https://github.com/corinnekrych/aerogear-ios-push/blob/AGPUSH-1232.sendMetrics/push-sdk-swiftTests/AGPushAnalyticsTests.swift) test case.

**Comment by cvasilak** [comment]
apart from it worked great using the HelloWorld demo PR objc :+1:

**Comment by corinnekrych** [comment]
Unit test does not run on Xcode 6.3 :(

Just created https://issues.jboss.org/browse/AGIOS-448 and https://issues.jboss.org/browse/AGIOS-449 to follow on not to block this PR (as not directly related to it). I'll send different PRs for those too.

**Comment by matzew** [comment]
thanks, landed on 1.x branch (a571005)

**Comment by matzew** [comment]
@corinnekrych @cvasilak can we have release (e.g. -beta.1) of this ObjC library ?

**Pull request merged**
