### PR TITLE
Migrate to CocoaPods 1.0.1

### PR DESCRIPTION
**Pull request by corinnekrych**
@jcesarmobile mind a review?

### CODE REVIEW

**Comment by jcesarmobile** [comment]
LGTM

**Comment by jcesarmobile** [comment]
The project have some old CocoaPods 0.39 files that should be removed.
libPods.a (Inside Frameworks folder)
Pods-push-sdkTests.debug.xcconfig (Inside Pods folder)
Pods-push-sdkTests.release.xcconfig (Inside Pods folder)

**Comment by corinnekrych** [comment]
@jcesarmobile I've done the cleaning, let me turn on travis for this branch

**Comment by corinnekrych** [comment]
Actually I don't have admin right on this  repo, @matzew must have the rights, could we turn on travis for '1.x_dev' branch?

**Comment by jcesarmobile** [comment]
It looks good to me, but let's wait for travis

**Comment by matzew** [comment]
@corinnekrych can you rebase ?

**Comment by corinnekrych** [comment]
@jcesarmobile ok to merge with happy travis?

**Comment by jcesarmobile** [comment]
Yes

**Pull request merged**
